vscode:
  extensions:
    - yandeu.five-server
    - HansUXdev.bootstrap5-snippets
    - naumovs.color-highlight
    - pranaygp.vscode-css-peek
    - idleberg.emoji-code
    - ecmel.vscode-html-css
    - kisstkondoros.vscode-gutter-preview
    - jock.svg

ports:
  - port: 5555
    onOpen: open-preview
